name: GitHub Readme YouTube Cards
on:
    schedule:
        #At 12:00 AM, only on Friday
        - cron: "0 0 * * FRI"
        workflow_dispatch:
            jobs:
                build:
                    runs-on: ubuntu-latest
                    # Allow the job to commit to the repository
                    permissions:
                        contents: whrite
                        # Run the GitHub Readme YouTube Cards action
                        steps:
                            - uses: DenverCoder1/github-readme-youtube-cards@main
                            with:
                                channel_id: UCrSNGU2jDSCmwE2dRFVLssw